server:
  port: 8001
spring:
  security:
    user:
      name: admin #设置默认登录用户名
      #设置默认登录密码 不设置会在控制台打印出，默认用户名是user
      password: admin
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: l(=8gp_04h*&
    driver-class-name: com.mysql.cj.jdbc.Driver
    minPoolSize: 3
    maxPoolSize: 10
    maxLifetime: 20000
    borrowConnectionTimeout: 30
    loginTimeout: 30
    mainteanceInterval: 60
    maxIdleTime: 60
## mybatis配置
mybatis:
  mapper-locations: classpath:dao/*.xml
  #  type-aliases-package: com.example.entity
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出sql语句
    map-underscore-to-camel-case: true #开启驼峰命名转换
  # mybatis使用分页插件
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql