server:
  port: 3344
spring:
  application:
    name: goudong-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GitHubFeiLong/springcloud-config.git
          search-paths:
            - springcloud-config
      #读取分支
      label: main

  #rabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    virtual-host: /vhost01

## rabbitmq 相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

# eureka 客户端配置
eureka:
  instance:
    prefer-ip-address: true #使用IP地址注册
    hostname: localhost # 实例主机名，如果不配置，服务名转host:port格式时host为系统生成的ASUS_PC，无法访问
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向注册中心注册id（ip 和端口）
    lease-renewal-interval-in-seconds: 5 #发送心跳的间隔
    lease-expiration-duration-in-seconds: 10 #续约到期的时间
  client:
    service-url:
      defaultZone: http://eureka7000:7000/eureka
