server:
  port: 8001
spring:
  application:
    name: goudong-user-server
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false # 关闭ribbon
  datasource: #数据库
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: l(=8gp_04h*&
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  flyway: ## flyway数据迁移
    #是否开启
    enabled: false
    locations: classpath:db/migration #迁移脚本的位置，默认db/migration
    baseline-on-migrate: true
    table: flyway_schema_history # 记录历史记录的表名称
    out-of-order: false
## mybatis配置
mybatis:
  mapper-locations: classpath:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出sql语句
    map-underscore-to-camel-case: true #开启驼峰命名转换
  # mybatis使用分页插件
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# eureka 客户端配置
eureka:
  instance:
    prefer-ip-address: true #使用IP地址注册
    hostname: localhost # 实例主机名，如果不配置，服务名转host:port格式时host为系统生成的ASUS_PC，无法访问
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向注册中心注册id（ip 和端口）
    lease-renewal-interval-in-seconds: 5 #发送心跳的间隔
    lease-expiration-duration-in-seconds: 10 #续约到期的时间
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui/index.html # 点击客户端的信息跳转到swagger页面
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ # 将服务注册到两个注册中心时用逗号隔开

