server:
  port: 9527
spring:
  application:
    name: goudong-gateway

  #网关配置（1.配置，2.代码）
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh1 #payment_route #路由的id，没有固定的规则，但是要唯一，建议使用服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://GOUDONG-PAYMENT-SERVER #使用微服务名进行路由
          predicates:
            - Path=/api/payment/demo1/** #断言，路径相匹配的进行路由
            #- Cookie After...Header....

        - id: payment_routh2 #payment_route #路由的id，没有固定的规则，但是要唯一，建议使用服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://GOUDONG-PAYMENT-SERVER #使用微服务名进行路由
          predicates:
            - Path=/api/payment/demo2/** #断言，路径相匹配的进行路由

# eureka 客户端配置
eureka:
  instance:
    prefer-ip-address: true #使用IP地址注册
    hostname: localhost # 实例主机名，如果不配置，服务名转host:port格式时host为系统生成的ASUS_PC，无法访问
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向注册中心注册id（ip 和端口）
    lease-renewal-interval-in-seconds: 5 #发送心跳的间隔
    lease-expiration-duration-in-seconds: 10 #续约到期的时间
  client:
    service-url:
      defaultZone: http://eureka7000:7000/eureka

