server:
  port: 81
spring:
  application:
    name: goudong-order-server-consul81
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}